package deb

import (
	"bufio"
	"bytes"
	"context"
	"fmt"
	"io"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/quantmind-br/upkg/internal/ui"
	"github.com/spf13/afero"
)

// convertWithDebtapProgress converts a DEB package to Arch package with progress tracking
//
//nolint:gocyclo // debtap conversion involves multiple IO streams and search fallbacks.
func (d *DebBackend) convertWithDebtapProgress(ctx context.Context, debPath, outputDir, expectedPkgName string, progress *ui.ProgressTracker) (string, error) {
	// Run debtap with quiet mode (-q) and skip interactive prompts (-Q)
	convertCtx, cancel := context.WithTimeout(ctx, 30*time.Minute)
	defer cancel()

	// Convert to absolute path since we're changing working directory
	absDebPath, err := filepath.Abs(debPath)
	if err != nil {
		return "", fmt.Errorf("failed to get absolute path: %w", err)
	}

	d.Log.Debug().
		Str("deb_path", absDebPath).
		Str("output_dir", outputDir).
		Msg("running debtap conversion")

	// Execute debtap with explicit working directory
	// Using -Q for fully automated conversion, then fix dependencies afterwards
	cmd := exec.CommandContext(convertCtx, "debtap", "-q", "-Q", absDebPath)
	cmd.Dir = outputDir // Set working directory so debtap creates package here

	stdoutPipe, err := cmd.StdoutPipe()
	if err != nil {
		return "", fmt.Errorf("failed to capture debtap stdout: %w", err)
	}

	stderrPipe, err := cmd.StderrPipe()
	if err != nil {
		return "", fmt.Errorf("failed to capture debtap stderr: %w", err)
	}

	startErr := cmd.Start()
	if startErr != nil {
		return "", fmt.Errorf("failed to start debtap: %w", startErr)
	}

	var stdoutBuf, stderrBuf bytes.Buffer

	stdoutDone := make(chan struct{})
	go func() {
		defer close(stdoutDone)
		reader := io.TeeReader(stdoutPipe, &stdoutBuf)
		scanner := bufio.NewScanner(reader)
		for scanner.Scan() {
			d.Log.Debug().
				Str("line", scanner.Text()).
				Msg("debtap stdout")
		}
		if scanErr := scanner.Err(); scanErr != nil {
			d.Log.Warn().Err(scanErr).Msg("failed to read debtap stdout")
		}
	}()

	stderrDone := make(chan struct{})
	go func() {
		defer close(stderrDone)
		reader := io.TeeReader(stderrPipe, &stderrBuf)
		scanner := bufio.NewScanner(reader)
		for scanner.Scan() {
			d.Log.Debug().
				Str("line", scanner.Text()).
				Msg("debtap stderr")
		}
		if scanErr := scanner.Err(); scanErr != nil {
			d.Log.Warn().Err(scanErr).Msg("failed to read debtap stderr")
		}
	}()

	start := time.Now()
	progressDone := make(chan struct{})
	go func() {
		ticker := time.NewTicker(1 * time.Second)
		defer ticker.Stop()
		for {
			select {
			case <-ticker.C:
				progress.UpdateIndeterminateWithElapsed("Converting DEB to Arch", time.Since(start))
			case <-progressDone:
				return
			}
		}
	}()

	err = cmd.Wait()
	close(progressDone)
	<-stdoutDone
	<-stderrDone

	if err != nil {
		d.Log.Error().
			Err(err).
			Str("stdout", stdoutBuf.String()).
			Str("stderr", stderrBuf.String()).
			Msg("debtap command failed")
		return "", fmt.Errorf("debtap conversion failed: %w\nStderr: %s", err, stderrBuf.String())
	}

	d.Log.Debug().
		Str("stdout", stdoutBuf.String()).
		Str("stderr", stderrBuf.String()).
		Msg("debtap conversion completed")

	// Find generated .pkg.tar.* file
	// Debtap creates package in current working directory, not in temp dir!

	// First try temp dir (in case debtap behavior changes)
	tempPattern := filepath.Join(outputDir, "*.pkg.tar.*")
	files, err := filepath.Glob(tempPattern)

	if err != nil {
		d.Log.Error().
			Err(err).
			Str("pattern", tempPattern).
			Msg("temp dir glob search failed")
		return "", fmt.Errorf("failed to search for generated package: %w", err)
	}

	if len(files) == 0 {
		// Search in the original package directory (where debtap typically creates the output)
		pkgDir := filepath.Dir(debPath)
		pkgPattern := filepath.Join(pkgDir, "*.pkg.tar.*")
		d.Log.Debug().
			Str("pkg_dir", pkgDir).
			Str("pattern", pkgPattern).
			Msg("searching in package directory")

		pkgFiles, globErr := filepath.Glob(pkgPattern)
		if globErr != nil {
			d.Log.Error().Err(globErr).Str("pattern", pkgPattern).Msg("package dir glob search failed")
		} else {
			files = append(files, pkgFiles...)
		}
	}

	if len(files) == 0 {
		// List all files in output directory for debugging
		allFiles, readDirErr := afero.ReadDir(d.Fs, outputDir)
		if readDirErr != nil {
			d.Log.Error().Err(readDirErr).Str("output_dir", outputDir).Msg("failed to list temp dir contents")
		}
		var fileList []string
		for _, f := range allFiles {
			fileList = append(fileList, f.Name())
		}
		d.Log.Error().
			Strs("files_in_dir", fileList).
			Str("output_dir", outputDir).
			Msg("no arch package generated by debtap in any location")
		return "", fmt.Errorf("no arch package generated by debtap (searched temp, working, and pkg dirs)")
	}

	d.Log.Debug().
		Strs("found_files", files).
		Str("expected_pkg_name", expectedPkgName).
		Msg("found generated packages")

	// Filter files to find the one matching expected package name
	var matchingFiles []string
	for _, file := range files {
		baseName := filepath.Base(file)
		// Package files are named like: pkgname-version-release-arch.pkg.tar.*
		if strings.HasPrefix(baseName, expectedPkgName+"-") ||
			strings.HasPrefix(baseName, strings.ReplaceAll(expectedPkgName, "_", "-")+"-") {
			matchingFiles = append(matchingFiles, file)
		}
	}

	// If we found matching files, use the most recent one
	if len(matchingFiles) > 0 {
		// Sort by modification time (most recent first)
		if len(matchingFiles) > 1 {
			// Get file info for sorting
			type fileWithTime struct {
				path    string
				modTime time.Time
			}
			var filesWithTime []fileWithTime
			for _, f := range matchingFiles {
				info, err := d.Fs.Stat(f)
				if err == nil {
					filesWithTime = append(filesWithTime, fileWithTime{path: f, modTime: info.ModTime()})
				}
			}
			// Sort by modification time descending
			for i := 0; i < len(filesWithTime)-1; i++ {
				for j := i + 1; j < len(filesWithTime); j++ {
					if filesWithTime[j].modTime.After(filesWithTime[i].modTime) {
						filesWithTime[i], filesWithTime[j] = filesWithTime[j], filesWithTime[i]
					}
				}
			}
			if len(filesWithTime) > 0 {
				return filesWithTime[0].path, nil
			}
		}
		return matchingFiles[0], nil
	}

	// No exact match found, log warning and use the most recent file
	d.Log.Warn().
		Str("expected", expectedPkgName).
		Strs("found", files).
		Msg("no package matching expected name, using first available")

	return files[0], nil
}

// isDebtapInitialized checks if debtap has been initialized
func isDebtapInitialized() bool {
	// Debtap stores its database in /var/cache/debtap/
	debtapCacheDir := "/var/cache/debtap"
	fs := afero.NewOsFs()

	// Check if cache directory exists
	if info, err := fs.Stat(debtapCacheDir); err != nil || !info.IsDir() {
		return false
	}

	// Check if essential database files exist (created during initialization)
	essentialFiles := []string{
		"debian-main-packages-files",
		"ubuntu-packages-files",
		"virtual-packages",
	}

	foundCount := 0
	for _, filename := range essentialFiles {
		filePath := filepath.Join(debtapCacheDir, filename)
		if _, err := fs.Stat(filePath); err == nil {
			foundCount++
		}
	}

	// Require at least 2 of the 3 essential files to be present
	return foundCount >= 2
}

// extractPackageInfoFromArchive reads .PKGINFO from an Arch package archive
// to discover the package name and version that pacman will register.
func extractPackageInfoFromArchive(pkgPath string) (*packageInfo, error) {
	cmd := exec.Command("bsdtar", "-xOf", pkgPath, ".PKGINFO")

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("failed to read .PKGINFO from archive: %w (stderr: %s)", err, strings.TrimSpace(stderr.String()))
	}

	info := &packageInfo{}
	lines := strings.Split(stdout.String(), "\n")
	for _, line := range lines {
		switch {
		case strings.HasPrefix(line, "pkgname = "):
			info.name = strings.TrimSpace(strings.TrimPrefix(line, "pkgname = "))
		case strings.HasPrefix(line, "pkgver = "):
			info.version = strings.TrimSpace(strings.TrimPrefix(line, "pkgver = "))
		}
	}

	if info.name == "" {
		return nil, fmt.Errorf("pkgname not found in .PKGINFO")
	}

	return info, nil
}
