run:
  modules-download-mode: readonly
  tests: true

linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 8
    min-occurrences: 5
  gosec:
    excludes:
      - G204
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - gosec
        - unparam
        - goconst
        - revive
    - path: _test\.go
      text: 'G404:'
  exclude-dirs:
    - third_party
    - builtin
    - examples
