run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    # - gosimple      # Simplify code
    - govet         # Examines Go source code and reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Comprehensive static analysis
    - unused        # Checks for unused constants, variables, functions and types
    - gosec         # Security problems
    # - gofmt         # Checks whether code was gofmt-ed
    # - goimports     # Checks import ordering
    - misspell      # Finds commonly misspelled English words
    - unparam       # Reports unused function parameters
    - unconvert     # Remove unnecessary type conversions
    - goconst       # Finds repeated strings that could be replaced by a constant
    - gocyclo       # Computes cyclomatic complexity
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for general use

  gocyclo:
    min-complexity: 15

  gosec:
    excludes:
      - G204  # Subprocess launched with variable - needed for package installation

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - unparam

    # Exclude specific gosec rules for test files
    - path: _test\.go
      text: "G404:"  # Weak random number generator (fine for tests)

  max-issues-per-linter: 0
  max-same-issues: 0

# output:
#   formats:
#     - format: colored-line-number
#   print-issued-lines: true
#   print-linter-name: true
#   sort-results: true
